// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  /**
   # @ngdoc function
   # @name iter001App.controller:OrderCtrl
   # @description
   # # OrderCtrl
   # Controller of the iter001App
  */

  angular.module('iter001App').controller('OrderCtrl', function($scope) {
    return $scope.awesomeThings = ['HTML5 Boilerplate', 'AngularJS', 'Karma'];
  });

}).call(this);
