// Generated by CoffeeScript 1.4.0
(function() {
  'use strict';

  /**
  # @ngdoc overview
  # @name iter001App
  # @description
  # # iter001App
  #
  # Main module of the application.
  */

  angular.module('iter001App', ['ngAnimate', 'ngAria', 'ngCookies', 'ngMessages', 'ngResource', 'ngRoute', 'ngSanitize', 'ngTouch']).config(function($routeProvider) {
    $routeProvider.when('/', {
      templateUrl: 'views/main.html',
      controller: 'MainCtrl'
    }).when('/about', {
      templateUrl: 'views/about.html',
      controller: 'AboutCtrl'
    }).when('/order', {
      templateUrl: 'views/order.html',
      controller: 'OrderCtrl'
    }).otherwise({
      redirectTo: '/'
    });
  });

}).call(this);
